#pragma once

enum RawTileType
{
	RT_NONE = 0,
	RT_BLOCK = OT_BLOCK,
	RT_FLOOR = OT_FLOOR,
	RT_BLOCK_RANDOM = 1,
	RT_FLOOR_RANDOM = 2,
	RT_TRAP_RANDOM = 3,
	RT_MONSTER_RUSH = 4,
	RT_PORTAL = 5,
	RT_STAGE_PORTAL = 6,
	RT_LASER_1 = 7,
	RT_LASER_2 = 8,
	RT_LASER_3 = 9,
	RT_ELECTRIC = 10,
	RT_COMPUTER = 11,
	RT_MONSTER_PLANT = 12,
	RT_MONSTER_DEVIL = 13,
	RT_MONSTER_BOSS_FIRST = 14,
	RT_VENDING_MACHINE = 15,
};

